name: Deployment
on:
  workflow_dispatch:

jobs:
  test:
    environment: qa
    runs-on: ubuntu-latest
    env:
      PORT: 3000
    steps:
      - uses: actions/checkout@v3
      - id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: make install
      - run: make start & npx wait-on --timeout 5000 http-get://127.0.0.1:$PORT
        env:
          MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME }}
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGODB_CLUSTER_ADDRESS: ${{ secrets.MONGODB_CLUSTER_ADDRESS }}
      - run: make test
        env:
          CI: 1
      - run: make reports
